application: imagingbuddy
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /img
  static_dir: public/img

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: .*
  script: banner.main.app

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: jinja2
  version: latest
